### ISSUE TITLE
Issue when running the gbppd command

### ISSUE THREAD

**Issue by Pognondeceo** [mcdxn/google-books-preview-pages-downloader#3]
I've got this error on the console when running the gbppd.start command: 
```
ƒ (){
            observer = new MutationObserver(callback);
            observer.observe(book, { attributes: true, childList: true, subtree: true });
            intervalId = setInterval(movePage, 500
```
Here is the log file. 

[books.google.mg-1632089861440.log](https://github.com/mcdxn/google-books-preview-pages-downloader/files/7193035/books.google.mg-1632089861440.log)
…

**Comment by mcdxn** [comment]
Hi Pognondeceo,

I just tested the code again and it is working. 

Thanks for the log. Looking at the attached log you, please make sure you put an opening and closing parentheses when calling the start and finish functions. For example, to start gbppd, you need to type gbppd.start() and to finish it gbppd.finish(). The parentheses are important.

**Comment by Pognondeceo** [comment]
Hi. You were right. Missing parentheses where the issue. Your script even makes the scrolling task automatically for the user.  😃

Thank you.
