### ISSUE TITLE
Full-texts with no PDF download option

### ISSUE THREAD

**Issue by Geremia** [mcdxn/google-books-preview-pages-downloader#5]
Thank you for this JavaScript. It was useful for downloading [_Esquisse d'une histoire de l'exégèse latine au moyen âge_](https://books.google.com/books?id=ihEXAAAAIAAJ) (1944), which previews 100% of his pages, yet for some reason there is no PDF download option ("No eBook available").

Are there other books on Google Books that preview 100% of the pages yet don't have a PDF download option?

**Comment by mcdxn** [comment]
No idea.
